### ISSUE TITLE
Tasks for *.json configuration export

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/ml-gradle#175]
It would be great if you could tell gradle to export a *.json configuration file for a resource (database, role, etc.) . This could become an easy way to migrate an existing installation to become redeployable with Gradle.

**Comment by sastafford** [comment]
I've always used the management API to export the resources I've needed.  

Example: http://localhost:8002/manage/v2/databases/Documents/properties?format=json

I take this response, save it to disk, and modify the required properties.  Plus the management API does not require you to specify every property, so your configuration would only be the delta from the defaults.  

The below snippet includes a token that gets resolved.  

    {
     "database-name": "%%DATABASE%%",
     "uri-lexicon": true,
     "collection-lexicon": true
    }

**Comment by RobertSzkutak** [comment]
Right. I think automating this with a task `gradle export databases=123,roles=A,B,C,users=X,Y,Z` or similar would make bringing large projects into ml-gradle a cinch. Could also be used to develop a Roxy migrater that just reads the ml-config.xml and then executes the appropriate export task.

**Comment by rjrudin** [comment]
I like this idea, but one downside to it is that the Manage API of course will export the entire database configuration. One of the benefits of the Manage API is that your e.g. database payload only has to specify what you want to change. Other than a database-name being required, everything else is optional. So it's very easy to see what's actually configured for a database. Exporting the whole database makes that difficult to understand. 

There's also a question of what to name the file that the resource is written to. That's easy for something that has a clear "name" property in it, but it's more difficult for things like roles, as roles have to be loaded in a certain order when one depends on another to be loaded first. Well actually - ml-gradle could punt on this and require the user to specify a filename (it couldn't just be logged to stdout, because Gradle itself writes some things to stdout too, such as task names as they're invoked). 

Overall, it's an optimization over a feature - host:8002/manage/api - that makes the job pretty easy already.

**Comment by rjrudin** [comment]
Just an FYI, this is being built out in ml-app-deployer first - 98% of the code will be there, then we'll add some Gradle tasks on top of it here.

**Comment by rjrudin** [comment]
2.7.0 will have a first cut of this that supports servers, databases, forests, and some security resources. Wiki page forthcoming.

**Comment by rjrudin** [comment]
mlExportResources now exists, as documented at https://github.com/marklogic-community/ml-gradle/wiki/Exporting-resources
