### ISSUE TITLE
mlDeploy with multiple environments

### ISSUE THREAD

**Issue by alan-johnson** [marklogic-community/ml-gradle#197]
Question about using ml-gradle along with the properties plugin to support different gradle<-environment>.properties . I downloaded the example properties-project which functions fine when setting the -PenvironmentName=  setting. However, when using -PenvironmentName=dev along with mlDeploy, the mlHost property doesn't seem to get replaced with the new value in my "gradle-dev.properties" file.

Is this an issue or am I just using -PenvironmentName incorrectly?

**Comment by rjrudin** [comment]
Ack. Just realized I put the plugins in the wrong order. The properties plugin has to be applied first, then ml-gradle.

I just fixed the proeprties-project example project. I'll get a release of 2.7.1 out over this weekend that fixes the "mlNewProject" task so that it puts the plugins in the right order.

**Comment by alan-johnson** [comment]
Thanks Rob! I didn't realize from reading the properties plugin README that order was important.
