### ISSUE TITLE
Export modules from existing installation

### ISSUE THREAD

**Issue by eouthwaite** [marklogic-community/ml-gradle#203]
mlExportResources does not currently export carefully hand-crafted REST APIs or App Server modules

The work-around that I have found is to use the [capture feature in Roxy](http://grtjn.blogspot.co.uk/2014/10/capturing-marklogic-applications-with.html), then copy the code across.

**Comment by rjrudin** [comment]
Updated title to make it clear that it's modules that need to be exported

**Comment by rjrudin** [comment]
@eouthwaite Where did you run into a need for this? The current thought for migrating from Roxy to ml-gradle is that the resources need to be exported so that ml-config.xml doesn't have to be converted into Management API payloads. But the source files that are in the modules database are assumed to be in the Roxy project already, in which case simply copying them from one directory to another should suffice.

**Comment by eouthwaite** [comment]
Exporting a working copy of marklogic-workflow ( https://github.com/marklogic-community/marklogicworkflow ) that had been installed using mljsadmin ( https://github.com/marklogic-community/mlnodetools ) in order to migrate it to a better-supported deployment tool.

**Comment by rjrudin** [comment]
Adding this to 3.1.0 - this should be a nice exercise for someone looking to use DMSDK, which is good at exporting documents.

**Comment by rjrudin** [comment]
There's now "mlExportModules". The description, which includes the various ways that its behavior can be configured:

Export modules matching a URI pattern of ** (can be overridden via -PuriPattern) from the database defined by mlModulesDatabaseName (can be overridden via -PdatabaseName) to the last path defined by mlModulePaths (can be overridden via -PexportPath). For each module that cannot be exported, an error will be logged; an error will be thrown instead by setting -PlogErrors to false.
