### ISSUE TITLE
mlClearSchemasDatabase removes temporal configurations still in use

### ISSUE THREAD

**Issue by luisjmart** [marklogic-community/ml-gradle#243]
The task mlClearSchemasDatabase will remove everything from the schema db, including temporal configs, without checking that the configured temporal Collection is in used by existing documents. This will remove temporal protection from all documents, reject new temporal docs, and prevent from reconfiguring the temporal collections, since the collection name is now considered non-temporal.

To prevent affecting existing temporal documents, could we check if the temporal collections are empty first. Or, distinguish "system" created schemas and not delete those?

**Comment by rjrudin** [comment]
There's another ticket for this, and I don't know what the right approach is. 

I think somewhere, we need a task for clearing the schemas database so that e.g. an app can have a fresh set of schemas loaded. This is useful during development, just like it's useful to clear the modules or triggers database and do a fresh load of everything. So I think "mlClearSchemasDatabase" is working as designed - it's consistent with hitting the "clear" button on the schemas database. 

So perhaps a separate task is needed, which is "Clear everything in the schemas database except certain things", but we'd need definition of those certain things. 

I think a useful addition for mlClearSchemasDatabase would be to require a Gradle property to be specified - mlClearContentDatabase requires that for this same reason, i.e. an "are you sure" check.

**Comment by luisjmart** [comment]
I saw the related reload task. Makes sense that this task is the same as "clear" button. The main concern is removing temporal protection by accident. But I can see that is not a ml-gradle specific issue. Thanks for looking into it.

**Comment by rjrudin** [comment]
If you think of a way to define a more targeted "only remove these documents and/or these collections", let me know, I'll be glad to accept a PR for it or implement it.
