### ISSUE TITLE
Suggestions for enhancing mlLoadModules

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/ml-gradle#265]
I'd like to see arguments added to mlLoadModules and/or additional tasks to support the following:

1) Deploy all modules in ml-modules *
2) Deploy only a specific module or rest resource
3) Deploy only rest resources

`*` I've noticed in my own usage that mlLoadModules on its own doesn't always deploy every module I have but rather tends to deploy only the most recently modified modules. I think it would be worthwhile to consider making this the default behavior.

Btw, happy to help implement if you'd like me to.

**Comment by rjrudin** [comment]
@RobertSzkutak I'm assuming you mean "mlLoadModules" 

I like all of these ideas. ml-javaclient-util has plumbing built in for this already - there's a "ModulesFinder" interface. There's BaseModulesFinder, which is complicated only because it includes support for finding modules in jar files (needed for DHF), and then DefaultModulesFinder. It should be possible to create a more configurable subclass of BaseModulesFinder that allows for e.g. a regex and a boolean to control whether REST resources or deployed or not. 

The next step is how to expose that via properties in ml-app-deployer - i.e.

    gradle mlLoadModules -PrestRresource=true|false -PmoduleRegex=somepattern

Once a set of command-line args is agreed upon, it's a matter of modifying LoadModulesTask in ml-gradle so that it does some surgery on the DefaultModulesLoader that's normally created. DefaultModulesLoader depends on an instance of ModulesFinder, so you could provide your own implementation of ModulesFinder and swap it in. 

I think that's the basic roadmap for supporting this. Happy to review a PR for it!

**Comment by rjrudin** [comment]
Oh, and the reason mlLoadModules doesn't deploy modules by default is for the reason you mention - it looks at file timestamps and only loads what's been modified since it last loaded modules. mlReloadModules is what I run most of the time (when I'm not running mlWatch, which is almost always running) - it clears the modules database, deletes the timestamp properties file under ./build/ml-javaclient-util, and then loads all the modules. 

So my normal workflow is:

# Update whatever git branch I'm on
# Run gradle mlReloadMod mlWatch -i

**Comment by RobertSzkutak** [comment]
Thanks @rjrudin !

When you're working on projects with multiple inexperienced developers who abuse WebDav the ability to deploy sets of modules without clearing the database first is extremely helpful. Additionally, it can allow you to avoid brief application downtime by not wiping the entire modules db.

At the very least an argument to mlLoadModules like `--forceLoad=true` that ignores the timestamp logic would be great.

In my own experience there doesn't appear to be timestamp tracking per environment. So if I deploy to dev it will deploy recently modified modules but if I then deploy to QA nothing is deployed without a reload. I've also experienced (on Windows) that when you deploy for the first time using gradle nothing is deployed and you have to first run mlReloadModules before the timestamp tracking works.

**Comment by rjrudin** [comment]
@RobertSzkutak You can do the same as "forceLoad" today by combining two tasks:

    gradle mlDeleteModuleTimestampsFile mlLoadModules

Should be able to abbreviate that to "gradle mlDeleteMod mlLoadMod". And you can always combine them into your own task, e.g.

task myLoadModules(dependsOn: ["mlDeleteModuleTimestampsFile", "mlLoadModules"])

As for only loading some modules - that capability may be useful soon for a project I support for doing "hotfixes".

**Comment by rjrudin** [comment]
@RobertSzkutak There's now a "mlModulesRegex" property for specifying which modules to load; this will be in 3.3.0.

https://github.com/marklogic-community/ml-app-deployer/issues/220

For "only load REST resources" - I'd like to do a separate ticket for that, but I'm curious first - what's the use case for that? mlModulesRegex will let you easily load only options, or only services, or only transforms, and of course the regex could be expanded to specify two or more of them. I just haven't run into a reason to ever load just REST resources.
