### ISSUE TITLE
Comma separated mlConfigPath

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/ml-gradle#266]
I'd like to set up a project structure like : 

/ml-config/
  /all
  /dev
  /stage
  /prod

And then tell gradle to deploy the resources in all and the resources in a specific environment.

A comma separated mlConfigPath would be able to support this

**Comment by damonfeldman** [comment]
Rob - can you give some context for the types of use cases this will support (so if there's another structure or approach, that can be considered too).

**Comment by rjrudin** [comment]
I'm assuming the "so that" here is so that I can divide up my configuration files based on the environments that they pertain to, with "all" being for resources that are common to all environments. 

One solution to that problem is to use a single configuration directory and use a filename pattern - e.g. filename prefixes - to distinguish which environment a file is intended for, and then use the existing properties for including/excluding files. 

I like the directory idea though, it's a clean way of separating the files. Unfortunately, it's an invasive change within ml-app-deployer, as the AppConfig object currently has a single ConfigDir object. Expanding that to a List<ConfigDir> would impact every command. Or, "ConfigDir configDir" could stay, and then "List<ConfigDir> additionalConfigDirs" would be added, which would be a non-breaking change. Each command would still need to be updated though to account for the presence of multiple config dirs to look at.

This design could be achieved in the short term though via a task that mlDeploy depends on, which would copy everything in "all" and "dev" or "stage" or "prod" into another directory, which mlConfigPath would point to.

**Comment by rjrudin** [comment]
@RobertSzkutak Just an FYI, I'm looking into this in ml-app-deployer. I think the basic approach will be to deprecate the "ConfigDir configDir" on AppConfig, and use a "List<ConfigDir> configDirs" field instead. Then it's just a matter of switching every command to use the List. And to maintain backwards compatibility, if the List is empty or null, then the deprecated single ConfigDir will be used.

**Comment by rjrudin** [comment]
Wrapping this up - it'll be:

gradle -PmlConfigPaths=path/to/config1,path/to/config2,etc

Ended up not being a big change really.

**Comment by rjrudin** [comment]
Addressed via https://github.com/marklogic-community/ml-app-deployer/issues/219 .
