### ISSUE TITLE
Entity Services and generate content database and artifact files

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic-community/ml-gradle#311]
When I use the ml-gradle task `mlGenerateMdoleArtifacts`  and if I have  my own configuration of the content-database.json at `ml-config/databases/content-database.json`, after running the `mlGenerateModelArtifacts` task, I notice that a new content-database json file is created namey `content-database-GENERATED.json`. I have couple of questions regarding this

- Which database json file gets loaded when I do `mlRedploy` ?
- When I modify my model file and redo the `mlGenerateModelArtifacts` task, I also noticed that it does not delete the old `ml-modules/ext/entity-services` xqy file but adds `*-GENERATED.xqy` and so does the options.  Same goes for `ml-schemas`. which one do I need to use and which one does `ml tasks` uses ?

**Comment by rjrudin** [comment]
If content-database.json exists already, ml-gradle writes to content-database-GENERATED.json so that it doesn't disturb your existing database configuration (which may conflict with the generated file). You can then copy what you want from the generated file into content-database.json. 

This same approach is followed for each of the files generated for ES - if the file exists already, ml-gradle doesn't want to risk breaking something by trying to merge the new data with the existing file, so it creates a generated file instead. It's up to the user then to merge the generated file with the existing files.

**Comment by ravi-b-m** [comment]
Thank you
