### ISSUE TITLE
ml-gradle should take advantage of Gradle's incremental build mechanisms.

### ISSUE THREAD

**Issue by BillFarber** [marklogic-community/ml-gradle#312]
With some configurations, running mlDeploy can be rather time consuming. Additionally, when there is a change to just one of the resources, and mlDeploy is initiated, the complete process runs.

Since ml-gradle already has tasks defined for each of the resource types, we should be able to create a task that is capable of running the tasks for the updated resources while skipping the tasks for the resources that have not changed.

In general, we can use the built-in incremental mechanisms of Gradle. For instance:
mlDeployGroups {
    inputs.dir file("src/main/ml-config/groups")
    outputs.upToDateWhen { true }
}
mlDeployDatabases {
    dependsOn mlDeployGroups
    inputs.dir file("src/main/ml-config/databases")
    outputs.upToDateWhen { true }

}
task mlIncrementalDeploy(dependsOn: ['mlDeployDatabases']) { }

This example allows us to incrementally deploy databases and groups using the mlIncrementalDeploy task. The mlDeployGroups task will be skipped when there have been no changes to the groups resource.

Attached is a larger, though not comprehensive, example.
[sample-project.zip](https://github.com/marklogic-community/ml-gradle/files/1735210/sample-project.zip)

**Comment by rjrudin** [comment]
@BillFarber I tried this on mlDeploy but it didn't have any impact. Is this really only usable on the more fine-grained tasks of the form "mlDeploy(ResourceType)", such as mlDeployDatabases?

I see still a lot of value; e.g. one project I work on has dozens of roles and privileges, and those take a long time to process when only one has been updated. 

I don't know if it's possible yet, but instead of adding new task names, I think using a property would be nice, as a developer could then always enable this by adding the property to gradle.properties:

    gradle -Pincremental=true mlDeployDatabases

**Comment by rjrudin** [comment]
I take that back - if I have 20 roles in my security/roles directory, then incremental works if none of the files have been updated - i.e. mlDeployRoles won't do anything. But if I change one role, then mlDeployRoles processes all 20 role files. 

Based on your example, it seems the solution then is to stitch together a new "mlIncrementalDeploy" that is based on a bunch of mlDeploy* tasks. One problem is that's not how mlDeploy works - mlDeploy works by invoking a bunch of ml-app-deployer Command objects, it doesn't reuse all of the mlDeploy* tasks.

**Comment by rjrudin** [comment]
@BillFarber Going to close this in favor of what you're pursuing in ml-app-deployer
