### ISSUE TITLE
Dependencies between ml-module paths can cause mlDeploy to break 

### ISSUE THREAD

**Issue by eurochriskelly** [marklogic-community/ml-gradle#340]
**Issue:**

When there are ml-modules paths that have dependencies on each other, the services may fail to install if expected modules have not been loaded .

**Repro:**
- In my project I have the following:
```
app\ml-modules\
    ext\foo.xqy
    services\get-foo.xqy
lib\ml-modules\
    root\error-helper.xqy
```
- In `build.gradle`, both _lib/_ and _app/_ are added to `modulesPath`
- `ext/foo.xqy` imports `root/error-helper.xqy`

**Result**

- If `root/error-helper.xqy` is copied first, the REST service, `get-foo.xqy`, will get installed correctly.
- Otherwise it will fail 

This could potentially by loading all xquery files that don't require special steps before installing '_special_' files such as transforms and services

**Comment by rjrudin** [comment]
Does the problem happen you define mlModulePaths as:

    mlModulePaths=lib,app

I've had this same sort of setup for a few years on a project, and it should avoid the problem you mention because modules are loaded in the following order:

1. lib non-REST modules
1. lib REST modules
1. app non-REST modules
1. app REST modules

**Comment by krixeli** [comment]
Apologies for my delayed update.

In fact, I've reported this issue in a different software project which tries to mimic ml-gradle functionality (mlproj). I thought I was seeing the same thing happening with multiple project paths because non-REST modules appeared to be missing and the REST service installation was failing. 

In the end, there was an error in an XQuery module so I must have checked the wrong database. Sorry about that and thanks for the response.
