### ISSUE TITLE
Error Handling for Missing Parameters

### ISSUE THREAD

**Issue by mikerosiak** [marklogic-community/ml-gradle#363]
In a DHF deployment, a forest config file is expecting parameters for failover options.  If these parameters are not in the gradle.properties file, the variable name itself (e.g. %%mlCustomForestFailoverHosts%%) is left unreplaced in the JSON data, which results in an "Unable to parse JSON: Unexpected character (%)" error.  

Suggest that error handling flag this as a missing parameter before it gets to point of JSON parsing.

**Comment by rjrudin** [comment]
@mikerosiak This is a little tricky because the code would need to parse every input first as a string and look for certain patterns. "%%" as a token prefix/suffix can be customized as well. 

I think what's a little more feasible is for the code to catch that "Unable to parse JSON" error and then do the following:

1. Include the text read from the file - and after tokens are replaced - in the error message
1. Add to the error message a suggestion saying to look at the text to see if there are tokens that weren't replaced, and to ensure those tokens correspond to properties

How does that sound?

**Comment by mikerosiak** [comment]
@rjrudin I was thinking that the code that does the token replacement could raise an error when a token isn't found, since it already knows to leave the original text in there when not found.

Otherwise, your alternate suggestion [of looking at the unexpected character, comparing it to the token prefix, and adding to the error message if so] would be helpful.

**Comment by rjrudin** [comment]
@mikerosiak The code doesn't look for tokens, it instead iterates over every token in a map and replaces it with its value if it exists in the payload. So it doesn't have any knowledge of tokens that aren't replaced.

**Comment by rjrudin** [comment]
@mikerosiak What I'm going to do for now is a small tweak in ml-app-deployer so that on every POST/PUT call, if there's a failure, the request body will be logged, in addition to the response body (which is generated by the Manage API), which is already logged. 

That will at least quickly call attention to what was sent to the Manage API. 

Going to close this ticket and open a new one for ml-app-deployer 3.8.3.
