### ISSUE TITLE
mlReloadModules replaces any local changes in the /build/mlRestApi area

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/ml-gradle#364]
My current dev pattern (supported, I think by mlwatch etc.) is to make changes to code from importedPackages where it is unzipped in the /build directory.

mlReloadModules appears to also re-expand the package from the gradle cache, and clobbers local changes. It would be intuitive to separate out updating the code from a package from deploying.

**Comment by rjrudin** [comment]
@damonfeldman That behavior is intentional - I like that after hacking around on thirdparty modules under ./build, I can rely on mlReloadModules to give a completely fresh start - i.e. clear the modules database, and do a fresh load of both thirdparty and app modules. 

Thus, I don't think mlReloadModules should change, but a new task could be added. mlReloadModules simply depends on mlClearModules and mlLoadModules, and the latter depends on mlPrepareRestApiDependencies, which is what re-expands the package from the Gradle cache. 

I believe Gradle has an answer for this already - you can do:

    gradle mlReloadModules -x mlPrepareRestApiDependencies

That's not the easiest to remember and type, but try that out, it should address the issue.

**Comment by rjrudin** [comment]
@damonfeldman Going to close this because Gradle does provide an OOTB solution here, but let me know if you'd like to see a new task in ml-gradle that gets this done without the use of the "-x" flag. Would need a suggestion for a name for this task - I definitely want to keep "mlReloadModules" the way it is.
