### ISSUE TITLE
Add a task to perform index comparison i.e. configuration file with current DB configuration prior deployment

### ISSUE THREAD

**Issue by pankajsahu-11** [marklogic-community/ml-gradle#374]
Hi Team,
We are part of preferred MarkLogic client/partner team and need a new ml-gradle task with following functionality which would be helpful while multiple projects are using same configuration file and migrate from DEV to QA/PRD environments:

- perform comparison of indexes from configuration file with indexes present in DB 
- list down the indexes which would be added/removed as part of this deployment
- prompt for confirmation i.e. Yes/No prior proceeding with mlDeploy or configuration deployment

Regards...Pankaj Sahu

**Comment by rjrudin** [comment]
How soon are you needing this? Note that this is largely an exercise in comparing JSON documents, which could be done in custom Java or Groovy code in your build.gradle file. Have you tried doing that yet? https://github.com/marklogic-community/ml-gradle/wiki/Writing-your-own-task provides some guidance on writing a custom task that talks to the Manage API.

**Comment by rjrudin** [comment]
#415 adds "mlPreviewDeploy". It will show all changes as part of a deployment, not just index changes for a database. There's no confirmation with proceeding - that would just be a matter of running mlDeploy after confirming that the preview looks sufficient. 

I'm closing this because of #415 - try that out (will be in 3.11.0 which should be released in the next week or so), and if you feel strongly about a confirmation process, please write up a new ticket and describe how it would work and improve upon running mlPreviewDeploy and then mlDeploy.
