### ISSUE TITLE
Allow for configuration of granular privileges using ml-gradle config

### ISSUE THREAD

**Issue by derms** [marklogic-community/ml-gradle#378]
Currently, granular privileges require a resource id (rather than a resource-name) to be deployed.

https://docs.marklogic.com/guide/security/granular#id_54114

This is a problem as the resource id for a database is different on each ML environment (and even if the same database is redeployed on the same environment)

RFE has been raised to allow names in granular privileges - https://project.marklogic.com/jira/browse/RFE-4195

In the mean time, should detect when granular privileges are being deployed and replace the "name" in the config with the relevant id in the payload.

**Comment by rjrudin** [comment]
Is the request then to support including granular privileges in role definitions? Or when creating new privileges? I am guessing the former. 

Any ideas on how to identify a privilege as granular, or more specifically, as having a database name in it that needs to be replaced? Based on https://docs.marklogic.com/guide/security/granular#id_pgfId-1064458 , I think we'd need to support forest names and group names as well. 

Could rely on some magic format such as "{database:(name)}". 

There's then an ordering issue here. Privileges and roles are some of the first resources deployed, because initially, they had no dependencies on anything else (except each other). So privileges are deployed first, then roles, and then users. That part is important, because it allows for a "non-security" user to then be used for deploying everything else - i.e. after all the security stuff is deployed, a user without the security role can be used for the rest of the deployment, thereby minimizing the use of what is probably an admin user. But that falls apart if databases/forests/groups have to be deployed before roles are deployed.

**Comment by rjrudin** [comment]
I think until the Manage API supports resource names, this will need to be done via post-deploy custom tasks.
