### ISSUE TITLE
How to undeploy single resources ? e.g.: Remove a user created by the current ml-gradle project.

### ISSUE THREAD

**Issue by kosed** [marklogic-community/ml-gradle#384]
Say you have deployed a set of users, each in its own config file,
Then you want to remove some of them but not all.
How can this be done ?

Just removing the related files from your config folder will not do it as it is not going to be "noticed" by ml-gradle.

The user example is just a sample and this can certainly be extended to any type of config file.
Running mlundeployXXX (with initial config) followed by mldeployXXX (with new config) in a row can be an option but at least only if run transactionally.

I am not sure though regarding the effects with mlDeployDatabases for example.
Are database actually going to be deleted and recreated ? In this case this option would be ruled out.
Another concern here is that the Manage API (at least some of them), as of the writing time of this post, do not take a transaction parameter.

A broader question here might be "should we/how to" maintain some kind of state in ml-gradle (As done with the modules deployment timestamp) ?

Ideas ?

**Comment by rjrudin** [comment]
What I've done for production applications is define a task like this:

    task deleteOldResources(type: com.marklogic.gradle.task.MarkLogicTask) {
      description = "Delete ML resources that are no longer in version control"
      doLast {
        // e.g. getManageClient().delete("/manage/v2/roles/some-role")
      }
    }

And for tickets for a release that require deleting resources, we add calls to the Manage API to this task to delete the resource. 

As for ml-gradle remembering resources that used to be on the filesystem but no longer are... I think managing that state would be tricky. The obvious risk is that ml-gradle deletes a resource that a user doesn't want deleted, and it wouldn't be apparent that ml-gradle is going to delete it because its managing some state in a file that the user wouldn't necessarily be aware of. 

In general, I think it's best to require a user to be explicit about deleting anything (hence why the "confirm" property must be set when running mlUndeploy).

**Comment by rjrudin** [comment]
Closing this as I don't think it'll be wise for ml-gradle to get in the business of remembering what resource files used to exist.
