### ISSUE TITLE
No info logging of where modules are loaded to

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/ml-gradle#392]
mlLoadModules with -i reports files loaded, but not the DB. This is probably in -d output, but will be quite obscured by volume of logging. To complete the picture of what was done, the target modules DB would be helpful. Output looks like:

```

> Task :mlLoadModules 
Putting task artifact state for task ':mlLoadModules' into context took 0.0 secs.
Up-to-date check for task ':mlLoadModules' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.
Initializing new instance of ModulesLoader
Loading asset modules from dir: /Users/dfeldman/ProjectRepos/declarative-mapper/build/mlRestApi/ml-unit-test/ml-modules
Initializing ExecutorService 
Initializing ExecutorService 
Writing 16 files
Writing: /test/css/tests.css
Writing: /test/css/jquery.gritter.css
Writing: /test/js/jquery-1.6.2.min.js
 
[...]

rs.sjs
Writing: /test/suites/Error/expression-compileErrors.sjs
Writing: /test/test-helper.xqy
Shutting down ExecutorService

Wrote 151 documents to MarkLogic
Writing resource services source for ml-unit-test
```

**Comment by rjrudin** [comment]
This looks trivial - it's a small change in ml-javaclient-util. I'll open a ticket there and close this one.

**Comment by rjrudin** [comment]
Question first - where do you think the database name should be logged? And which calls should be logged - the calls to log non-REST modules, or REST modules, or both? 

I ask because this may get tricky with the Java Client. To load non-REST modules, a DatabaseClient is created that talks to port 8000 and specifies a database. But to load REST Modules, a DatabaseClient is created that talks to a custom REST port, but no database is specified because there's no need to specify one - the REST port suffices. 

What that means is for the code that loads REST modules, it likely has a DatabaseClient whose "getDatabase" method returns null. It could log the port. 

In light of that, I'm now thinking that the port should always be logged, and the database should be as well, if it's not null. Sound right?

**Comment by rjrudin** [comment]
As for where it's logged - looks trivial to log the port/database before/after each batch of non-REST modules is written (there's support for batching in case there's a large number of these modules). There's debug logging in place for the "before", and info logging for the "after" - I can change the "before" to info. 

As for REST extensions - this is an area where I wish the Java Client just provided this kind of logging itself. It'll be a matter of surrounding each call to the Java Client with before/after logging, as there's a different call for each kind of REST extension.
