### ISSUE TITLE
previous digest authentication with same nonce failed, returning null

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic-community/ml-gradle#396]
This is for a project I'm migrating from roxy to ml-gradle. I'd appreciate any insights as to why I'm getting:
`previous digest authentication with same nonce failed, returning null`

```
Writing: /views/correspondence/correspondence-editor-view.xqy
Shutting down ExecutorService

Wrote 1021 documents to MarkLogic

> Task :mlDeployApp FAILED
Shutting down ExecutorService
Loading all non-asset modules from dir: src/main/ml-modules
Initializing ExecutorService 
Writing REST server configuration
Default document read transform: 
Transform all documents on read: null
Validate query options: true
Validate queries: false
Output debugging: false
Writing server configuration
previous digest authentication with same nonce failed, returning null
Releasing connection
:mlDeployApp (Thread[Task worker for ':',5,main]) completed. Took 2 mins 2.872 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> Local message: config/properties write failed: Unauthorized. Server Message: Unauthorized


```

gradle.properties:
```
mlPassword=admin
mlUsername=admin
```

build.gradle:
```
buildscript {
    repositories {
        maven {url 'http://developer.marklogic.com/maven2/'}
    }
}

plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'application'

    // This plugin allows you to create different environments
    // for your gradle deploy. Each environment is represented
    // by a gradle-${env}.properties file
    // See https://github.com/stevesaliman/gradle-properties-plugin
    // specify the env on the command line with:
    // gradle -PenvironmentName=x ...
    id 'net.saliman.properties' version '1.4.6'

    id "com.marklogic.ml-gradle" version "3.9.0"
}

apply plugin: 'distribution'
apply plugin: 'application'

dependencies {
    // Needed for loading modules into MarkLogic
    compile "com.marklogic:ml-gradle:3.9.0"
    compile "com.marklogic:ml-app-deployer:3.9.1"

    // https://mvnrepository.com/artifact/com.marklogic/marklogic-client-api
    compile group: 'com.marklogic', name: 'marklogic-client-api', version: '4.1.1'

}
task deploy_dls (type: com.marklogic.gradle.task.ServerEvalTask, group: 'Converted Roxy build step') {
	xquery = '      @logger.info(%Q{#{xq}})' +
'      #@logger.info(r)' +
'  end' +
'end'
}

```

**Comment by rjrudin** [comment]
See https://github.com/marklogic/marklogic-jena/issues/72 for the same issue. The upcoming ml-gradle 3.10.0 release will include marklogic-client-api 4.1.1.

In the meantime, try setting the following property so that the loading of modules isn't multi-threaded, which is what seems to cause the bug (though this will work once 4.1.1 is being used);

    mlModulesLoaderThreadCount=1

**Comment by janmichaelyu** [comment]
I also tried cloning and downloading the marklogic-data-movement-components projec, update the marklogic-client-api  dependency to 4.1.1, publish both that and ml-gradle to local repo, then forced my project to use that local ml-gradle. 

That still gave the "previous digest authentication with same nonce failed, returning null" error.

```

compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
+--- com.marklogic:ml-app-deployer:3.9.0
|    +--- org.slf4j:jcl-over-slf4j:1.7.22
|    |    \--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|    +--- com.marklogic:ml-javaclient-util:3.8.1
|    |    +--- com.marklogic:marklogic-client-api:4.0.3.1 -> 4.1.1
```

**Comment by rjrudin** [comment]
You have to force marklogic-client-api usage at the "buildscript" level in Gradle to impact the plugins - try this:

```
buildscript {
	dependencies {
		classpath "com.marklogic:marklogic-client-api:4.1.1"
	}
}
```

**Comment by janmichaelyu** [comment]
I tried that and I still get the error.
scan is available here: https://scans.gradle.com/s/ywvhfdpcukjaq

**Comment by rjrudin** [comment]
Do you still get the same "previous nonce" error?

I am thinking this issue is specific to the Java Client and how your app server is configured. Take a look at https://github.com/marklogic-community/ml-gradle/wiki/Debugging-module-loading#debugging-module-loading-without-involving-ml-gradle - this shows an example of writing a Gradle task that uses the Java Client to load a module. In your case though, you'd want to load a transform or make a call to /v1/config/properties - see the link on that page to the javadocs, or just check the ML docs on how to do that. 

The goal here is if you can get a simple Java program using the ML Java Client to make a call to /v1/config/properties, then we can get it working via ml-gradle, as all ml-gradle does is construct a DatabaseClient and then uses the APIs on that object.

**Comment by janmichaelyu** [comment]
Yes, I still get the "previous nonce" error. Alright, I'll try that. Thanks!

**Comment by Elgaeb** [comment]
This did come down to an issue with our application server. It's a sorta-but-not-really rest server and that was causing the issues. Deploying a vanilla rest server and using that to load resolved the issue. This can be closed.

**Comment by Elgaeb** [comment]
Thanks!
