### ISSUE TITLE
Rename mlRestAPI to something more descriptive

### ISSUE THREAD

**Issue by aajacobs** [marklogic-community/ml-gradle#420]
Currently maven packages with MarkLogic code are loaded through a command named  'mlRestApi' in build.grade files.  But because these packages don't have to be loaded as resource extensions, the name of mlRestApi is misleading.  Recommend changing it to something like mlPackages in build.gradle.

**Comment by rjrudin** [comment]
Some current candidates:

- mlPackage = not great because the term "package" is already in use in MarkLogic (the Packaging API), and I think it's too broad for what's currently just a set of modules (I think we ultimately want a "package" to refer to a set of modules, schemas, and resources)
- mlModules = not great because that's all the name of the modules directory (src/main/ml-modules)
- mlLibrary
- mlModulePackage
- mlDependency = this might be my favorite because it's referring to a dependency

**Comment by jamesagardner** [comment]
I favor mlPackage, with hopes that it can be expanded to include more pieces of a MarkLogic application's configuration as its use is expanded.

**Comment by derms** [comment]
what about mlSource ? or do you feel like it is an overloaded term?
or mlSourceModules?

**Comment by aajacobs** [comment]
Is there something that prevents the current method of packaging using maven from including what you suggest (e.g.,  modules, schemas and resources)?  Or have we just not been using it that way?  I think of these as packages.

**Comment by rjrudin** [comment]
mlBundle it is - https://github.com/marklogic-community/ml-gradle/wiki/Bundles
