### ISSUE TITLE
Renaming a TDE does not remove old TDE

### ISSUE THREAD

**Issue by netdance** [marklogic-community/ml-gradle#455]
if you rename a TDE, say from ml-schemas/tde/one.tde to ml-schemas/tde/two.tde, mlDeploy does not delete one.tde.  Which means now you have two TDEs differing only in their URI, which means duplicated rows.  Is this intended behavior?  I'd expect instead to remove the old TDE, and possibly trigger a reindex.

**Comment by aajacobs** [comment]
Automatically disabling a TDE will cause a reindex, which may not be desired behavior at the time.  An alternative may be to warn the user about the need to disable/reindex/delete a TDE when they have deleted a TDE in a DHF/ml-gradle project and execute a gradle task that updates TDEs.  Ml-gradle could then prompt them to perform the action now and pay the reindexing cost immediately (and force them to confirm the decision like when doing an mlUndeploy), or to let them ignore the outdated TDE with the warning that they're on their own to disable and reindex later if they want to get rid of it.  

Would be really nice if ml-gradle could auto-detect outdated TDEs and give a warning during every TDE-related task so admins don't forget to take care of business, but not sure that's feasible.

**Comment by rjrudin** [comment]
When would ml-gradle do this? It would need to listen for filesystem changes - e.g. via https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html - but is a Gradle task guaranteed to be running when the TDE template is renamed? Or is the expectation that when  mlLoadSchemas runs, it should first do a sync between what's in the project and what's in ML and possibly delete the TDE that's no longer in the project? Would you be okay with it deleting TDE templates that aren't in the project? 

I think this needs a lot more design work before something can proceed, as we're talking about ml-gradle automatically deleting things, and we need to be very clear about when it should do that.

**Comment by jamesagardner** [comment]
I think it's a very reasonable default behavior that ml-gradle or any other deployment tool not remove or delete resources on a MarkLogic cluster unless explicitly told to do so, as removing resources can have very bad consequences to running systems.  Though I think it would be beneficial for ml-gradle to identify when extra resources exist on the MarkLogic cluster that are not a part of the resources being applied by ml-gradle.  Identifying these resources in two ways could be useful:

1.  Warning log statement when gradle is applying the resources, and identifies an un-managed resource in the MarkLogic cluster
1. Differences file per MarkLogic cluster that is updated to keep track of identified differences.  This could be a precurser to additional tooling that allows a tool to take corrective actions.  I think we'd need a separate story to discuss those actions, and how to implement them, but here are my initial thoughts:
    - **Import** -  Some way to grab the resource from the MarkLogic cluster and have it automatically added to the ml-gradle resource directory.  This could be a fun way to capture an otherwise non-managed MarkLogic cluster and get started with ml-gradle.
    - **Ignore** - Ignore the resource differences, consider no longer sending warning messages for ignored differences.  I can see why some resources in the environment shouldn't belong in the ml-gradle resources as they are temporary or there for experimentation and not quite ready to be a part of a baseline.
    - **Delete** - Remove the resource from the MarkLogic cluster so that it matches the ml-gradle resources.  Some environments may want a command line switch to enforce this behavior during a specific ml-gradle run to prevent rogue resources on a given MarkLogic cluster.

Let me know if the above suggestions should be filed as a separate issue as my thoughts are broader that just TDE templates.

**Comment by rjrudin** [comment]
@netdance  @aajacobs  @jamesagardner Revisiting - the underlying capability here is "Delete TDEs in a database that are not associated with any files in my project". Automating that - like when a user renames a TDE file - is a separate matter. 

I am wondering how useful that capability really is. It seems mostly like a local development task - I don't see it being used in production much. But in local development, it's not uncommon to load a TDE via something like qconsole for ad hoc hacking around. And if you rename a TDE file in your project, you may not want to lose the ad hoc TDE templates you've created. 

The current approach for this is to just delete a template from qconsole, which is a lot easier now that qconsole lets you delete a document by pointing and clicking. And that document is likely easy to find, as schema databases don't tend to have hundreds of documents in them. 

For now, my opinion is that using qconsole is easy enough, so I'm going to close this ticket. I'm open to a "Delete some set of documents that aren't represented by files in my project" capability, but it will need to be carefully thought-out design to avoid documents being deleted that shouldn't be deleted - it may need some interactivity so that ml-gradle can say "Here's what I'm going to delete, please confirm".
