### ISSUE TITLE
Error with mlDeploySecurity

### ISSUE THREAD

**Issue by luisjmart** [marklogic-community/ml-gradle#471]
Deploying security config with default permissions and custom execute privilege causes error on vertion 3.15.0

gradle mlDeploySchema 

Execution failed for task ':mlDeploySecurity'.
> Graph has cycles

**Comment by rjrudin** [comment]
Going to need an example of how to reproduce this.

**Comment by rjrudin** [comment]
If you can provide an example, please provide it here. My guess would be that the privileges are referring to roles, but roles are created after privileges (since roles can have privileges). 

If you need a privilege to have roles, you'll need a custom Gradle task to update the privileges to have roles. 

I'm thinking that alternatively, ml-gradle (really ml-app-deployer) could create the privileges without roles first, then deploy the roles, then redeploy the privileges, this time with roles.

**Comment by luisjmart** [comment]
I simplified a config illustrating the problem. Looks like the issue is with nested roles and default permissions. I think to remove the cycle, I just need to add the role directly to the users instead of nesting the permissions-role
[security.zip](https://github.com/marklogic-community/ml-gradle/files/3315882/security.zip)
