### ISSUE TITLE
mlUnitTest -PrunCodeCoverage output not found

### ISSUE THREAD

**Issue by lonesloane** [marklogic-community/ml-gradle#482]
When running from the command line, runCodeCoverage does not seem to produce any output on the file system.

**Comment by rjrudin** [comment]
The issue is that the mlUnitTest task asks marklogic-unit-test to format the results based on JUnit's expected schema, and that results in the coverage data being dropped. I think the solution will involve writing the "raw" marklogic-unit-test results to a separate directory. 

To address this though, I'm going to move this into the marklogic-unit-test project, as the guts of UnitTestTask in ml-gradle should really move into marklogic-unit-test. That will allow for specifying a path for the JUnit-formatted results and for the raw results, which will include the coverage data.

**Comment by rjrudin** [comment]
Addressing via https://github.com/marklogic-community/marklogic-unit-test/issues/82 .
