### ISSUE TITLE
mlCreateTransform is creating resources in "test" instead of main "ml-modules"

### ISSUE THREAD

**Issue by s3-4v** [marklogic-community/ml-gradle#507]
Hi, in a Grove project running ml-gradle version 3.14, for one dev, mlCreateTransform is apparently creating the resources in an unexpected location:

```shell
$ ./gradlew mlCreateTransform -PtransformName=test-transform -PtransformType=sjs

> Task :mlCreateTransform
Creating new transform at ...\compas\marklogic\test\ml-modules\transforms\test-transform.sjs
Creating new transform metadata file at ...\compas\marklogic\test\ml-modules\transforms\metadata\test-transform.xml
```

I'm not able to reproduce this result -- the same command with the same project repo for me is creating the resources in the proper path.

I've requested the output of `.gradlew -- version` from the other developer so we can compare configurations.

Thanks.

**Comment by rjrudin** [comment]
mlCreateResource and mlCreateTransform both have to pick a module path from the list of module paths. They currently pick the last path to avoid any issues with writing the modules to an mlBundle-associated directory. But if you then have e.g. mlModulePaths=src/main/ml-modules,src/test/ml-modules - then they get written to the test directory, since that's the last path.

I'm now thinking though that when this change was made, it was due to mlModulePaths being modified to have a bundle path in it for the purposes of tweaking bundle code while running mlWatch. That's a much less important use case than supporting what should be a common use case of appending src/test/ml-modules to mlModulePaths.

So no need for any logging or gradle output - I'll modify these tasks to use the first module path. I think well over 80% of the time, that should be the appropriate location.
