### ISSUE TITLE
Enhance mlWatch to delete modules as files are deleted

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#512]
I have a modules directory with files that I either deleted or renamed, mlWatch uploaded the new updates but now my code on the server has old code.

Can mlWatch be updated to know when a file was deleted, I expect this would therefore also cover deletes, and then issue a documentDelete to MarkLogic?

**Comment by rjrudin** [comment]
There was another issue related to this, where the general concept was - After I've deleted files, can some ml-gradle task delete the corresponding resource/module from the database? 

I said "no" to that - I think the example was a schema file being deleted - because I think it's too risky for ml-gradle to assume it should delete something in the database, just because it's not within the set of project files that ml-gradle is aware of. For example, someone can always create a resource or load a module/schema via the Admin GUI / qconsole. It would be surprising and potentially very annoying if ml-gradle deleted that. 

mlWatch is a little different because it's a running process and it could be enhanced to listen to filesystem events - e.g. https://howtodoinjava.com/java8/java-8-watchservice-api-tutorial/ . 

I've thought about adding this feature - I run into a need for it on DHF when I e.g. rename unit test files, but the old files are left behind and still visible in the test runner GUI. "mlReloadModules" solves that problem though, and that's what I've used for several years now. 

Also, enhancing mlWatch wouldn't help for another common use case - i.e. I start my day off, I rebase off the develop branch, and that includes the deletion of some modules. I don't have mlWatch running yet, so it's not there to listen for file deletions. In that use case - I just run mlReloadModules or mlRedeploy immediately after updating from develop. 

One other item, this being a source of complexity - a documentDelete would work fine for everything under ./root, but REST extensions under ./services and ./transforms and ./options would require more effort - each of those need a specific DELETE call to be made to the appropriate REST API endpoint.

So with all that said, I'm wondering how valuable an enhancement to mlWatch would be vs just relying on mlReloadModules? What problems does the latter run into?

**Comment by prestonmcgowan** [comment]
Your thoughtful response is helpful in understanding the complexity.
I ran into this issue with my test cases, as you also identified. Like you recommended, I find myself killing mlWatch, running mlReloadModules, and then restarting mlWatch.

Does mlReloadModules also load the ./services, ./transforms, ./options, and schemas?

I am wondering if mlWatch could cover the easy use case of me deleting my test cases, libraries, etc. and just warning about other modifications.

If you can identify the updates to the other items, but it is more involved; just have mlWatch run mlReloadModules or put out a recommendation to run mlReloadModules to the console.

**Comment by rjrudin** [comment]
Closing this, as I think for the time being, mlReloadModules gets the job done.
