### ISSUE TITLE
Loading data only if no content exists at the specified URI

### ISSUE THREAD

**Issue by ahwitz** [marklogic-community/ml-gradle#526]
(sorry for spamming this repo; this one actually belongs here, I think?)

It seems like the `src/main/ml-data` strategy for importing data on `mlDeploy` will automatically overwrite files, and a quick browse through the `GenericFileLoader` file made it seem like there wasn't an existing option to test if the document exists anywhere.

It's been a while since I touched `mlcp`, but in looking through [these docs](http://docs.marklogic.com/9.0/guide/mlcp/import#id_23879), I couldn't find anything that seemed to directly relate to overwriting/testing for existence. I don't know if the  `com.marklogic:mlcp` Java interface exposes different options, and I also don't know if I missed something.

The reason I'm posting this in this repository is that, while the `ml-data` solution would be a bit easier to work with, an MLCP-like one is also totally fine, and I may be missing another option entirely - is there currently any way to load data only if the destination files don't already exist?

**Comment by rjrudin** [comment]
For mlcp, you'd need to use a transform to e.g. check to see if the URI exists already, and if so, you'd return null from the transform so that nothing is written. 

That capability doesn't exist with the ml-data solution, which is only intended to be a super-simple way to load some data, often just for demos. I've only used it once; I almost always reach for mlcp since it has so many more features and flexibility. 

I'd rather not add this to ml-data because the best way to do this is via some chunk of code within ML - i.e. an mlcp or REST transform, which can very efficiently do a check to see if the document exists. For that to work with ml-data, which uses the REST API, it would need to depend on some existing REST transform. That's not really practical. 

An option in the near future will be for GenericFileLoader to use a Data Services endpoint, where the user could specify that endpoint. A user could then configure that endpoint to perform any logic desired.
