### ISSUE TITLE
Unable to create replicas for schemas database with property-driven design and mlPrintForestPlan

### ISSUE THREAD

**Issue by bshalke** [marklogic-community/ml-gradle#556]
**Describe the bug**
Running **gradlew.bat -Pdatabase=repsrv-schemas mlPrintForestPlan** produces the following error:

```
Execution failed for task ':mlPrintForestPlan'.
> Not enough hosts exists to create 1 replicas for database 'repsrv-schemas'; possible hosts, which may include the host with the primary forest and thus cannot have a replica: [ip-10-64-17-207.us-west-2.compute.internal]
```

Running **gradlew.bat -Pdatabase=repsrv-modules mlPrintForestPlan** succeeds without error.

Tested locally with a single host and remotely with 3 hosts in a cluster

**To Reproduce**
- Extract attached project
- Populate gradle.properties with connection info
- Run gradlew.bat -Pdatabase=repsrv-schemas [mlPrintForestPlan]

**Expected behavior**
mlPrintForestPlan works for all databases without error.

[marklogic-develop-set1.zip](https://github.com/marklogic-community/ml-gradle/files/4799562/marklogic-develop-set1.zip)

**Comment by rjrudin** [comment]
First, I recommend upgrading from 3.9.0 to 3.17.0, which is the latest 3.x release. This includes a number of improvements and bug fixes pertaining to forest replica creation. 

Then, starting in 3.11.0, the default schema and trigger database names (where default is based on the value of mlAppName) are included by default in the value of the mlDatabasesWithForestsOnOneHost property - see https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#database-and-forest-properties . 

I believe the issue is that when a database is configured to only have primary forests on one host, the mlPrintForestPlan task isn't taking that into account when it considers the hosts that replicas can live on. You can somewhat circumvent this behavior by adding "mlDatabasesWithForestsOnOneHost=" to gradle.properties, though that only works if you're fine with your schema database having primary forests on multiple hosts (which can be perfectly fine for your app too). 

I verified that replicas are created correctly for databases with forests on only one host; the bug appears to just be for previewing what replicas will be created. 

I'll open up a separate ticket in ml-app-deployer to fix the bug with preview. In the meantime, I recommend the following:

- Use ml-gradle 3.17.0
- Add mlDatabasesWithForestsOnOneHost= to gradle.properties
