### ISSUE TITLE
Can't import custom tasks into other .gradle files

### ISSUE THREAD

**Issue by ahwitz** [marklogic-community/ml-gradle#579]
**Describe the bug**
Am currently trying to make custom classes that extend RunFlowTask per the bottom block of [this page](https://github.com/marklogic-community/ml-gradle/wiki/Dynamically-creating-tasks), and because of how wide the scope of the project is, it makes more sense to create the classes in one file and import them into another. Seems like there are two options to do this:

- Creating the class in a *.gradle file, then calling `apply from:` doesn't seem to work, because Gradle doesn't share classes between files like that.
- Using the Gradle buildSrc directory (what is recommended) doesn't work with dataHub, because applying the plugin (the only way I can find right now to expose the tasks) results in the following error:
```
A problem occurred evaluating project ':buildSrc'.
> Failed to apply plugin [id 'com.marklogic.ml-data-hub']
   > Please initialize your project first by running the 'hubInit' Gradle task, or update it by running the 'hubUpdate' Gradle task
```

**To Reproduce**
1. In a functional DH gradle repo, create `/buildSrc/build.gradle` file that at least contains:
```
allprojects {
  apply plugin: "java"
  apply plugin: "com.marklogic.ml-gradle"
  apply plugin: "com.marklogic.ml-data-hub"
}
```
2. Create a `buildSrc/src/main/groovy/TestTask.groovy` file that at least contains:
```
import org.gradle.api.tasks.*
import com.marklogic.gradle.task.*

public class IngestTask extends com.marklogic.gradle.task.RunFlowTask
{
    @TaskAction
    void runFlow() {
        println "hello"

        super.runFlow()
    }
}
```
3. Add the following to `/build.gradle`:
```
task hello (type: IngestTask)
{

}
```
4. Run `gradle hello`

**Expected behavior**
We'd like to be able to define custom classes that are used in multiple places. Not sure what the best way to do it is, but the way that Gradle recommends doesn't seem to be functional with the ml-gradle/data-hub classes.

**Comment by ahwitz** [comment]
Just found that `ext.IngestTask = IngestTask` then `(type: ext.IngestTask)` works, so this can be closed if `buildSrc` isn't a desired path.

**Comment by rjrudin** [comment]
This is a DHF-specific issue, and the DHF Gradle plugin is complaining because when it's applied against the buildSrc project, it checks the directory (buildSrc) to see if a DHF project has been initialized, and of course there isn't one there. 

So you can definitely use buildSrc on a DHF project, but you can't apply the DHF plugin in the buildSrc directory (unless of course, you don't mind stubbing out a DHF project in there, but that would seem pretty confusing). 

Also, I think a more typical use case for buildSrc is to create custom classes, but not necessarily custom tasks. I would lean putting your RunFlowTask instances in your main build.gradle file - here's an example of doing that - https://github.com/marklogic/marklogic-data-hub/blob/develop/examples/reference-entity-model/build.gradle#L22 

There are likely other ways to slim down your build.gradle file - I'd start by extracting stuff that doesn't depend on the DHF Gradle plugin.

**Comment by ahwitz** [comment]
Noted and understood.

> Also, I think a more typical use case for buildSrc is to create custom classes, but not necessarily custom tasks.

Just for reference, though, we are actually doing custom classes, similar to the `class IngestTask extends com.marklogic.gradle.task.MlcpTask` example on the page I linked to. We have a lot of  `RunFlowTask` derivatives that have probably 20 or so lines of customization on top of the base RunFlowTask, 10-ish of which they have in common with each other. We were trying to condense the lines in common into another class, and I'm fairly certain we do meet that typical use case. `ext.IngestTask` works well enough for the time being, though.
