### ISSUE TITLE
Test server deployed before test database

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#584]
I am using

    mlConfigPaths=src/main/hub-internal-config,src/main/ml-config,src/test/ml-config

src/main/ml-config does not contain test-server nor test-database configs, those are in src/test/ml-config.

Yet, when I mlDeploy, it seems to attempt creating the test-server before creating the test-database.

I am using plugins { id "com.marklogic.ml-data-hub" version "5.2.6" }, so not entirely sure which version of ml-gradle is behind this. Fairly confident this is an ml-gradle issue though.

Is there a way to force datahub to use a particular version of ml-gradle? Can you just specify a particular version of ml-gradle next/after the datahub plugin?

**Comment by grtjn** [comment]
I discovered after some experimentation that the test-content database was simply not deployed. It was omitted in mlDeployDatabases. Not sure if it is datahub or not, haven't ruled that out yet. Managed to get past this by renaming xxx-test-content db to xxx-tst-content db.. :-(

**Comment by rjrudin** [comment]
Do you have mlTestRestPort set?

**Comment by grtjn** [comment]
yes

**Comment by rjrudin** [comment]
The behavior of mlRestPort/mlTestRestPort isn't really known in DHF, since DHF doesn't make use of those properties. If a database file is being ignored by DHF, that's definitely a bug for DHF, which you can open in the DHFPROD JIRA project - though since this is 5.2.x, I do recommend trying it against 5.4.x first.

**Comment by grtjn** [comment]
Could still influence each other, I think. My latest tests were with DHF 5.4.2 by the way. I'll open a github ticket against DHF since I have no longer access to JIRA. I need to produce a small repro first though.

**Comment by rjrudin** [comment]
When ml-app-deployer processes database files, it does say - if this is the "main" content database (which is based on mlAppName, which is not used by DHF), and there's no file for an associated "test" content database, then it will create/update the "test" content database based on the config for the "main" content database. 

I can't think of any reason why a file would be ignored though - try using "-i" to see what directories/files are processed when mlDeployDatabases is run. 

It's always best though that when you're using DHF and you run into a bug, start with a bug in DHF because DHF is not using ml-gradle as-is - it imports and extends/modifies it.

**Comment by grtjn** [comment]
-i shows the test/ml-config is considered, but the db config file is ignored. I'll start a new thread at DHF...
